server:
  port: 8084

spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      routes:
        - id: users_route
          uri: http://user:8080/users
          predicates:
            - Path=/users/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://my-release-keycloak.default.svc.cluster.local/realms/master/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
